### ISSUE TITLE
Very nice

### ISSUE THREAD

**Issue by mrhasbean** [badabingbreda/cookie-connector-for-themer#1]
Great work! No issues, works a treat, but just wondering if you'd considered doing something similar to process URL parameters, or maybe even integrating it into this so that a cookie could be written based on a URL parameter? Currently using a manual method for showing / hiding content based on a URL parameter, but more options like this would be very useful.

**Comment by badabingbreda** [comment]
The conditional showing and hiding of content based on URL parameter(s) is something I can easily add.
Writing cookies based on URL parameters is something you'd normally do using a callback in your functions.php before sending anything to the browser, or, as with this plugin, using javascript and an ajax call to pass the variable to a cookie.

I'm sure I can add the conditional rule so you can show/hide nodes based on the existence of a URL parameter, will do.
